### ISSUE TITLE
emus/lgb.pkl missing from master

### ISSUE THREAD

**Issue by jgomezdans** [MarcYin/SIAC#8]
It appears that the `lgb.pkl` file is missing from the emus folder...
```
Traceback (most recent call last):
  File "do_siac.py", line 22, in <module>
    SIAC.SIAC_S2(output_s2_folder, jasmin=True)
  File "/XXX/.local/lib/python3.7/site-packages/SIAC-2.3.0-py3.7.egg/SIAC/SIAC_S2.py", line 40, in SIAC_S2
    rets = s2_pre_processing(s2_t, cams_dir, global_dem)
  File "/XXX/.local/lib/python3.7/site-packages/SIAC-2.3.0-py3.7.egg/SIAC/s2_preprocessing.py", line 185, in s2_pre_processing
    aot, tcwv     = do_aot_tcwv(aot_bands, tcwv_bands, cams_dir, obs_time, sun_ang_name, view_ang_name, dem, tcwv_name = None, aot_name = None)
  File "/XXX/.local/lib/python3.7/site-packages/SIAC-2.3.0-py3.7.egg/SIAC/s2_preprocessing.py", line 103, in do_aot_tcwv
    gbm      = joblib.load(file_path + '/emus/lgb.pkl')
  File "/XXX/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 590, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/XXX/.local/lib/python3.7/site-packages/SIAC-2.3.0-py3.7.egg/SIAC/emus/lgb.pkl'
```

**Comment by MarcYin** [comment]
This has been added.
